alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias bx='bundle exec'
alias bxfr='bundle exec foreman run'
alias bxfs='bundle exec foreman start'
alias webserver='python3 -m http.server'
alias penguins='mpv http://207.198.114.241:1935/qlive/edinburghzoopenguintwo.stream/playlist.m3u8'
alias pip-update-all='pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'
